<template>
  <div class="icon-grid">
		<IconPreview :selectIcon=selectIcon title="alarm-clock"><tap-icon-alarm-clock></tap-icon-alarm-clock></IconPreview>
		<IconPreview :selectIcon=selectIcon title="alarm-clock-fill"><tap-icon-alarm-clock-fill></tap-icon-alarm-clock-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="arrow-top-right"><tap-icon-arrow-top-right></tap-icon-arrow-top-right></IconPreview>
		<IconPreview :selectIcon=selectIcon title="arrow-top-right-fill"><tap-icon-arrow-top-right-fill></tap-icon-arrow-top-right-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="arrow-top-right-question"><tap-icon-arrow-top-right-question></tap-icon-arrow-top-right-question></IconPreview>
		<IconPreview :selectIcon=selectIcon title="arrow-top-right-question-fill"><tap-icon-arrow-top-right-question-fill></tap-icon-arrow-top-right-question-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="banknote"><tap-icon-banknote></tap-icon-banknote></IconPreview>
		<IconPreview :selectIcon=selectIcon title="banknote-fill"><tap-icon-banknote-fill></tap-icon-banknote-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="banknote-two"><tap-icon-banknote-two></tap-icon-banknote-two></IconPreview>
		<IconPreview :selectIcon=selectIcon title="banknote-two-fill"><tap-icon-banknote-two-fill></tap-icon-banknote-two-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="bell"><tap-icon-bell></tap-icon-bell></IconPreview>
		<IconPreview :selectIcon=selectIcon title="bell-dot-fill"><tap-icon-bell-dot-fill></tap-icon-bell-dot-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="bell-fill"><tap-icon-bell-fill></tap-icon-bell-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="bookmark"><tap-icon-bookmark></tap-icon-bookmark></IconPreview>
		<IconPreview :selectIcon=selectIcon title="bookmark-fill"><tap-icon-bookmark-fill></tap-icon-bookmark-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="box"><tap-icon-box></tap-icon-box></IconPreview>
		<IconPreview :selectIcon=selectIcon title="box-check"><tap-icon-box-check></tap-icon-box-check></IconPreview>
		<IconPreview :selectIcon=selectIcon title="box-fill"><tap-icon-box-fill></tap-icon-box-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="briefcase"><tap-icon-briefcase></tap-icon-briefcase></IconPreview>
		<IconPreview :selectIcon=selectIcon title="briefcase-fill"><tap-icon-briefcase-fill></tap-icon-briefcase-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="building"><tap-icon-building></tap-icon-building></IconPreview>
		<IconPreview :selectIcon=selectIcon title="building-fill"><tap-icon-building-fill></tap-icon-building-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="calendar"><tap-icon-calendar></tap-icon-calendar></IconPreview>
		<IconPreview :selectIcon=selectIcon title="calendar-fill"><tap-icon-calendar-fill></tap-icon-calendar-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="call-dialog-box"><tap-icon-call-dialog-box></tap-icon-call-dialog-box></IconPreview>
		<IconPreview :selectIcon=selectIcon title="call-left"><tap-icon-call-left></tap-icon-call-left></IconPreview>
		<IconPreview :selectIcon=selectIcon title="call-left-slash"><tap-icon-call-left-slash></tap-icon-call-left-slash></IconPreview>
		<IconPreview :selectIcon=selectIcon title="call-righ"><tap-icon-call-righ></tap-icon-call-righ></IconPreview>
		<IconPreview :selectIcon=selectIcon title="call-right-slash"><tap-icon-call-right-slash></tap-icon-call-right-slash></IconPreview>
		<IconPreview :selectIcon=selectIcon title="camera"><tap-icon-camera></tap-icon-camera></IconPreview>
		<IconPreview :selectIcon=selectIcon title="camera-fill"><tap-icon-camera-fill></tap-icon-camera-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="camera-plus"><tap-icon-camera-plus></tap-icon-camera-plus></IconPreview>
		<IconPreview :selectIcon=selectIcon title="car"><tap-icon-car></tap-icon-car></IconPreview>
		<IconPreview :selectIcon=selectIcon title="car-clock"><tap-icon-car-clock></tap-icon-car-clock></IconPreview>
		<IconPreview :selectIcon=selectIcon title="car-clock-fill"><tap-icon-car-clock-fill></tap-icon-car-clock-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="car-fill"><tap-icon-car-fill></tap-icon-car-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="car-slash"><tap-icon-car-slash></tap-icon-car-slash></IconPreview>
		<IconPreview :selectIcon=selectIcon title="car-slash-fill"><tap-icon-car-slash-fill></tap-icon-car-slash-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="car-spark"><tap-icon-car-spark></tap-icon-car-spark></IconPreview>
		<IconPreview :selectIcon=selectIcon title="card"><tap-icon-card></tap-icon-card></IconPreview>
		<IconPreview :selectIcon=selectIcon title="card-fill"><tap-icon-card-fill></tap-icon-card-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="card-left-arrow"><tap-icon-card-left-arrow></tap-icon-card-left-arrow></IconPreview>
		<IconPreview :selectIcon=selectIcon title="card-left-arrow-fill"><tap-icon-card-left-arrow-fill></tap-icon-card-left-arrow-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="card-plus"><tap-icon-card-plus></tap-icon-card-plus></IconPreview>
		<IconPreview :selectIcon=selectIcon title="card-plus-fill"><tap-icon-card-plus-fill></tap-icon-card-plus-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="card-right-arrow"><tap-icon-card-right-arrow></tap-icon-card-right-arrow></IconPreview>
		<IconPreview :selectIcon=selectIcon title="card-right-arrow-fill"><tap-icon-card-right-arrow-fill></tap-icon-card-right-arrow-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="card-spark"><tap-icon-card-spark></tap-icon-card-spark></IconPreview>
		<IconPreview :selectIcon=selectIcon title="card-spark-fill"><tap-icon-card-spark-fill></tap-icon-card-spark-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="card-time"><tap-icon-card-time></tap-icon-card-time></IconPreview>
		<IconPreview :selectIcon=selectIcon title="card-time-fill"><tap-icon-card-time-fill></tap-icon-card-time-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="check"><tap-icon-check></tap-icon-check></IconPreview>
		<IconPreview :selectIcon=selectIcon title="check-fill"><tap-icon-check-fill></tap-icon-check-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="circle-check"><tap-icon-circle-check></tap-icon-circle-check></IconPreview>
		<IconPreview :selectIcon=selectIcon title="circle-check-fill"><tap-icon-circle-check-fill></tap-icon-circle-check-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="circle-check-small"><tap-icon-circle-check-small></tap-icon-circle-check-small></IconPreview>
		<IconPreview :selectIcon=selectIcon title="circle-check-small-fill"><tap-icon-circle-check-small-fill></tap-icon-circle-check-small-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="circle-cross"><tap-icon-circle-cross></tap-icon-circle-cross></IconPreview>
		<IconPreview :selectIcon=selectIcon title="circle-cross-fill"><tap-icon-circle-cross-fill></tap-icon-circle-cross-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="circle-exclamation"><tap-icon-circle-exclamation></tap-icon-circle-exclamation></IconPreview>
		<IconPreview :selectIcon=selectIcon title="circle-exclamation-fill"><tap-icon-circle-exclamation-fill></tap-icon-circle-exclamation-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="circle-fill-1"><tap-icon-circle-fill-1></tap-icon-circle-fill-1></IconPreview>
		<IconPreview :selectIcon=selectIcon title="circle-fill-2"><tap-icon-circle-fill-2></tap-icon-circle-fill-2></IconPreview>
		<IconPreview :selectIcon=selectIcon title="circle-fill-3"><tap-icon-circle-fill-3></tap-icon-circle-fill-3></IconPreview>
		<IconPreview :selectIcon=selectIcon title="circle-fill-4"><tap-icon-circle-fill-4></tap-icon-circle-fill-4></IconPreview>
		<IconPreview :selectIcon=selectIcon title="circle-fill-5"><tap-icon-circle-fill-5></tap-icon-circle-fill-5></IconPreview>
		<IconPreview :selectIcon=selectIcon title="circle-fill-6"><tap-icon-circle-fill-6></tap-icon-circle-fill-6></IconPreview>
		<IconPreview :selectIcon=selectIcon title="circle-fill-7"><tap-icon-circle-fill-7></tap-icon-circle-fill-7></IconPreview>
		<IconPreview :selectIcon=selectIcon title="circle-fill-8"><tap-icon-circle-fill-8></tap-icon-circle-fill-8></IconPreview>
		<IconPreview :selectIcon=selectIcon title="circle-fill-9"><tap-icon-circle-fill-9></tap-icon-circle-fill-9></IconPreview>
		<IconPreview :selectIcon=selectIcon title="circle-information"><tap-icon-circle-information></tap-icon-circle-information></IconPreview>
		<IconPreview :selectIcon=selectIcon title="circle-information-fill"><tap-icon-circle-information-fill></tap-icon-circle-information-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="circle-minus"><tap-icon-circle-minus></tap-icon-circle-minus></IconPreview>
		<IconPreview :selectIcon=selectIcon title="circle-minus-fill"><tap-icon-circle-minus-fill></tap-icon-circle-minus-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="circle-more-fill"><tap-icon-circle-more-fill></tap-icon-circle-more-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="circle-outline-1"><tap-icon-circle-outline-1></tap-icon-circle-outline-1></IconPreview>
		<IconPreview :selectIcon=selectIcon title="circle-outline-2"><tap-icon-circle-outline-2></tap-icon-circle-outline-2></IconPreview>
		<IconPreview :selectIcon=selectIcon title="circle-outline-3"><tap-icon-circle-outline-3></tap-icon-circle-outline-3></IconPreview>
		<IconPreview :selectIcon=selectIcon title="circle-outline-4"><tap-icon-circle-outline-4></tap-icon-circle-outline-4></IconPreview>
		<IconPreview :selectIcon=selectIcon title="circle-outline-5"><tap-icon-circle-outline-5></tap-icon-circle-outline-5></IconPreview>
		<IconPreview :selectIcon=selectIcon title="circle-outline-6"><tap-icon-circle-outline-6></tap-icon-circle-outline-6></IconPreview>
		<IconPreview :selectIcon=selectIcon title="circle-outline-7"><tap-icon-circle-outline-7></tap-icon-circle-outline-7></IconPreview>
		<IconPreview :selectIcon=selectIcon title="circle-outline-8"><tap-icon-circle-outline-8></tap-icon-circle-outline-8></IconPreview>
		<IconPreview :selectIcon=selectIcon title="circle-outline-9"><tap-icon-circle-outline-9></tap-icon-circle-outline-9></IconPreview>
		<IconPreview :selectIcon=selectIcon title="circle-person"><tap-icon-circle-person></tap-icon-circle-person></IconPreview>
		<IconPreview :selectIcon=selectIcon title="circle-person-fill"><tap-icon-circle-person-fill></tap-icon-circle-person-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="circle-person-fill-1"><tap-icon-circle-person-fill-1></tap-icon-circle-person-fill-1></IconPreview>
		<IconPreview :selectIcon=selectIcon title="circle-plus"><tap-icon-circle-plus></tap-icon-circle-plus></IconPreview>
		<IconPreview :selectIcon=selectIcon title="circle-plus-fill"><tap-icon-circle-plus-fill></tap-icon-circle-plus-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="circle-question-fill"><tap-icon-circle-question-fill></tap-icon-circle-question-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="circle-star"><tap-icon-circle-star></tap-icon-circle-star></IconPreview>
		<IconPreview :selectIcon=selectIcon title="circle-star-fill"><tap-icon-circle-star-fill></tap-icon-circle-star-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="circle-thunder"><tap-icon-circle-thunder></tap-icon-circle-thunder></IconPreview>
		<IconPreview :selectIcon=selectIcon title="circle-thunder-fill"><tap-icon-circle-thunder-fill></tap-icon-circle-thunder-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="clipboard-clock"><tap-icon-clipboard-clock></tap-icon-clipboard-clock></IconPreview>
		<IconPreview :selectIcon=selectIcon title="clipboard-clock-fill"><tap-icon-clipboard-clock-fill></tap-icon-clipboard-clock-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="clips-together"><tap-icon-clips-together></tap-icon-clips-together></IconPreview>
		<IconPreview :selectIcon=selectIcon title="clock"><tap-icon-clock></tap-icon-clock></IconPreview>
		<IconPreview :selectIcon=selectIcon title="clock-arrow-circlepath"><tap-icon-clock-arrow-circlepath></tap-icon-clock-arrow-circlepath></IconPreview>
		<IconPreview :selectIcon=selectIcon title="clock-dashed"><tap-icon-clock-dashed></tap-icon-clock-dashed></IconPreview>
		<IconPreview :selectIcon=selectIcon title="clock-fill"><tap-icon-clock-fill></tap-icon-clock-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="clock-small"><tap-icon-clock-small></tap-icon-clock-small></IconPreview>
		<IconPreview :selectIcon=selectIcon title="clock-small-fill"><tap-icon-clock-small-fill></tap-icon-clock-small-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="copy"><tap-icon-copy></tap-icon-copy></IconPreview>
		<IconPreview :selectIcon=selectIcon title="copy-fill"><tap-icon-copy-fill></tap-icon-copy-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="coupon"><tap-icon-coupon></tap-icon-coupon></IconPreview>
		<IconPreview :selectIcon=selectIcon title="coupon-fill"><tap-icon-coupon-fill></tap-icon-coupon-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="coupon-puched"><tap-icon-coupon-puched></tap-icon-coupon-puched></IconPreview>
		<IconPreview :selectIcon=selectIcon title="coupon-puched-fill"><tap-icon-coupon-puched-fill></tap-icon-coupon-puched-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="cross"><tap-icon-cross></tap-icon-cross></IconPreview>
		<IconPreview :selectIcon=selectIcon title="cross-fill"><tap-icon-cross-fill></tap-icon-cross-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="default"><tap-icon-default></tap-icon-default></IconPreview>
		<IconPreview :selectIcon=selectIcon title="default-1"><tap-icon-default-1></tap-icon-default-1></IconPreview>
		<IconPreview :selectIcon=selectIcon title="default-2"><tap-icon-default-2></tap-icon-default-2></IconPreview>
		<IconPreview :selectIcon=selectIcon title="default-3"><tap-icon-default-3></tap-icon-default-3></IconPreview>
		<IconPreview :selectIcon=selectIcon title="default-4"><tap-icon-default-4></tap-icon-default-4></IconPreview>
		<IconPreview :selectIcon=selectIcon title="default-5"><tap-icon-default-5></tap-icon-default-5></IconPreview>
		<IconPreview :selectIcon=selectIcon title="default-6"><tap-icon-default-6></tap-icon-default-6></IconPreview>
		<IconPreview :selectIcon=selectIcon title="default-7"><tap-icon-default-7></tap-icon-default-7></IconPreview>
		<IconPreview :selectIcon=selectIcon title="default-8"><tap-icon-default-8></tap-icon-default-8></IconPreview>
		<IconPreview :selectIcon=selectIcon title="default-9"><tap-icon-default-9></tap-icon-default-9></IconPreview>
		<IconPreview :selectIcon=selectIcon title="default-fill"><tap-icon-default-fill></tap-icon-default-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="dialog-box-text"><tap-icon-dialog-box-text></tap-icon-dialog-box-text></IconPreview>
		<IconPreview :selectIcon=selectIcon title="dialog-box-text-fill"><tap-icon-dialog-box-text-fill></tap-icon-dialog-box-text-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="dialogbox-question"><tap-icon-dialogbox-question></tap-icon-dialogbox-question></IconPreview>
		<IconPreview :selectIcon=selectIcon title="diamond-arrow-turn-right"><tap-icon-diamond-arrow-turn-right></tap-icon-diamond-arrow-turn-right></IconPreview>
		<IconPreview :selectIcon=selectIcon title="diamond-arrow-turn-right-1"><tap-icon-diamond-arrow-turn-right-1></tap-icon-diamond-arrow-turn-right-1></IconPreview>
		<IconPreview :selectIcon=selectIcon title="dot-fill"><tap-icon-dot-fill></tap-icon-dot-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="double-check"><tap-icon-double-check></tap-icon-double-check></IconPreview>
		<IconPreview :selectIcon=selectIcon title="ear-slash"><tap-icon-ear-slash></tap-icon-ear-slash></IconPreview>
		<IconPreview :selectIcon=selectIcon title="envelope"><tap-icon-envelope></tap-icon-envelope></IconPreview>
		<IconPreview :selectIcon=selectIcon title="envelope-fill"><tap-icon-envelope-fill></tap-icon-envelope-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="envelope-open"><tap-icon-envelope-open></tap-icon-envelope-open></IconPreview>
		<IconPreview :selectIcon=selectIcon title="envelope-open-fill"><tap-icon-envelope-open-fill></tap-icon-envelope-open-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="exclamation"><tap-icon-exclamation></tap-icon-exclamation></IconPreview>
		<IconPreview :selectIcon=selectIcon title="exclamation-fill"><tap-icon-exclamation-fill></tap-icon-exclamation-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="eye"><tap-icon-eye></tap-icon-eye></IconPreview>
		<IconPreview :selectIcon=selectIcon title="eye-fill"><tap-icon-eye-fill></tap-icon-eye-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="eye-slash"><tap-icon-eye-slash></tap-icon-eye-slash></IconPreview>
		<IconPreview :selectIcon=selectIcon title="eye-slash-fill"><tap-icon-eye-slash-fill></tap-icon-eye-slash-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="face-sad"><tap-icon-face-sad></tap-icon-face-sad></IconPreview>
		<IconPreview :selectIcon=selectIcon title="face-sad-fill"><tap-icon-face-sad-fill></tap-icon-face-sad-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="face-smile"><tap-icon-face-smile></tap-icon-face-smile></IconPreview>
		<IconPreview :selectIcon=selectIcon title="face-smile-fill"><tap-icon-face-smile-fill></tap-icon-face-smile-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="finger-left-fill"><tap-icon-finger-left-fill></tap-icon-finger-left-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="finger-swipe-vertical"><tap-icon-finger-swipe-vertical></tap-icon-finger-swipe-vertical></IconPreview>
		<IconPreview :selectIcon=selectIcon title="finger-touch"><tap-icon-finger-touch></tap-icon-finger-touch></IconPreview>
		<IconPreview :selectIcon=selectIcon title="finger-up-fill"><tap-icon-finger-up-fill></tap-icon-finger-up-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="fire"><tap-icon-fire></tap-icon-fire></IconPreview>
		<IconPreview :selectIcon=selectIcon title="fire-fill"><tap-icon-fire-fill></tap-icon-fire-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="flag"><tap-icon-flag></tap-icon-flag></IconPreview>
		<IconPreview :selectIcon=selectIcon title="flag-fill"><tap-icon-flag-fill></tap-icon-flag-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="gas-station"><tap-icon-gas-station></tap-icon-gas-station></IconPreview>
		<IconPreview :selectIcon=selectIcon title="gas-station-fill"><tap-icon-gas-station-fill></tap-icon-gas-station-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="gear"><tap-icon-gear></tap-icon-gear></IconPreview>
		<IconPreview :selectIcon=selectIcon title="gear-fill"><tap-icon-gear-fill></tap-icon-gear-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="gift"><tap-icon-gift></tap-icon-gift></IconPreview>
		<IconPreview :selectIcon=selectIcon title="graduation-cap"><tap-icon-graduation-cap></tap-icon-graduation-cap></IconPreview>
		<IconPreview :selectIcon=selectIcon title="graduation-cap-fill"><tap-icon-graduation-cap-fill></tap-icon-graduation-cap-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="headphone"><tap-icon-headphone></tap-icon-headphone></IconPreview>
		<IconPreview :selectIcon=selectIcon title="headphone-fill"><tap-icon-headphone-fill></tap-icon-headphone-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="heart"><tap-icon-heart></tap-icon-heart></IconPreview>
		<IconPreview :selectIcon=selectIcon title="heart-broken-fill"><tap-icon-heart-broken-fill></tap-icon-heart-broken-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="heart-fill"><tap-icon-heart-fill></tap-icon-heart-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="helmets"><tap-icon-helmets></tap-icon-helmets></IconPreview>
		<IconPreview :selectIcon=selectIcon title="helmets-fill"><tap-icon-helmets-fill></tap-icon-helmets-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="home"><tap-icon-home></tap-icon-home></IconPreview>
		<IconPreview :selectIcon=selectIcon title="home-fill"><tap-icon-home-fill></tap-icon-home-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="hourglass"><tap-icon-hourglass></tap-icon-hourglass></IconPreview>
		<IconPreview :selectIcon=selectIcon title="hourglass-fill"><tap-icon-hourglass-fill></tap-icon-hourglass-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="image"><tap-icon-image></tap-icon-image></IconPreview>
		<IconPreview :selectIcon=selectIcon title="image-fill"><tap-icon-image-fill></tap-icon-image-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="image-two"><tap-icon-image-two></tap-icon-image-two></IconPreview>
		<IconPreview :selectIcon=selectIcon title="image-two-fill"><tap-icon-image-two-fill></tap-icon-image-two-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="info"><tap-icon-info></tap-icon-info></IconPreview>
		<IconPreview :selectIcon=selectIcon title="info-fill"><tap-icon-info-fill></tap-icon-info-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="keyboard"><tap-icon-keyboard></tap-icon-keyboard></IconPreview>
		<IconPreview :selectIcon=selectIcon title="keyboard-fill"><tap-icon-keyboard-fill></tap-icon-keyboard-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="lamp-spark-fill"><tap-icon-lamp-spark-fill></tap-icon-lamp-spark-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="line-three"><tap-icon-line-three></tap-icon-line-three></IconPreview>
		<IconPreview :selectIcon=selectIcon title="line-three-horizontal-decrease"><tap-icon-line-three-horizontal-decrease></tap-icon-line-three-horizontal-decrease></IconPreview>
		<IconPreview :selectIcon=selectIcon title="list-bullet"><tap-icon-list-bullet></tap-icon-list-bullet></IconPreview>
		<IconPreview :selectIcon=selectIcon title="loading"><tap-icon-loading></tap-icon-loading></IconPreview>
		<IconPreview :selectIcon=selectIcon title="location-left"><tap-icon-location-left></tap-icon-location-left></IconPreview>
		<IconPreview :selectIcon=selectIcon title="location-up"><tap-icon-location-up></tap-icon-location-up></IconPreview>
		<IconPreview :selectIcon=selectIcon title="lock"><tap-icon-lock></tap-icon-lock></IconPreview>
		<IconPreview :selectIcon=selectIcon title="lock-fill"><tap-icon-lock-fill></tap-icon-lock-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="lock-small"><tap-icon-lock-small></tap-icon-lock-small></IconPreview>
		<IconPreview :selectIcon=selectIcon title="lock-small-fill"><tap-icon-lock-small-fill></tap-icon-lock-small-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="magnifier"><tap-icon-magnifier></tap-icon-magnifier></IconPreview>
		<IconPreview :selectIcon=selectIcon title="magnifier-fill"><tap-icon-magnifier-fill></tap-icon-magnifier-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="map"><tap-icon-map></tap-icon-map></IconPreview>
		<IconPreview :selectIcon=selectIcon title="map-fill"><tap-icon-map-fill></tap-icon-map-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="medal"><tap-icon-medal></tap-icon-medal></IconPreview>
		<IconPreview :selectIcon=selectIcon title="medal-1"><tap-icon-medal-1></tap-icon-medal-1></IconPreview>
		<IconPreview :selectIcon=selectIcon title="medal-fill"><tap-icon-medal-fill></tap-icon-medal-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="medal-fill-1"><tap-icon-medal-fill-1></tap-icon-medal-fill-1></IconPreview>
		<IconPreview :selectIcon=selectIcon title="microphone"><tap-icon-microphone></tap-icon-microphone></IconPreview>
		<IconPreview :selectIcon=selectIcon title="microphone-fill"><tap-icon-microphone-fill></tap-icon-microphone-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="microphone-slash"><tap-icon-microphone-slash></tap-icon-microphone-slash></IconPreview>
		<IconPreview :selectIcon=selectIcon title="microphone-slash-fill"><tap-icon-microphone-slash-fill></tap-icon-microphone-slash-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="microphone-spark"><tap-icon-microphone-spark></tap-icon-microphone-spark></IconPreview>
		<IconPreview :selectIcon=selectIcon title="microphone-spark-fill"><tap-icon-microphone-spark-fill></tap-icon-microphone-spark-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="minus"><tap-icon-minus></tap-icon-minus></IconPreview>
		<IconPreview :selectIcon=selectIcon title="minus-fill"><tap-icon-minus-fill></tap-icon-minus-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="moon"><tap-icon-moon></tap-icon-moon></IconPreview>
		<IconPreview :selectIcon=selectIcon title="moon-fill"><tap-icon-moon-fill></tap-icon-moon-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="more-horizontal"><tap-icon-more-horizontal></tap-icon-more-horizontal></IconPreview>
		<IconPreview :selectIcon=selectIcon title="more-horizontal-fill"><tap-icon-more-horizontal-fill></tap-icon-more-horizontal-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="more-vertical"><tap-icon-more-vertical></tap-icon-more-vertical></IconPreview>
		<IconPreview :selectIcon=selectIcon title="more-vertical-fill"><tap-icon-more-vertical-fill></tap-icon-more-vertical-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="motorcycle"><tap-icon-motorcycle></tap-icon-motorcycle></IconPreview>
		<IconPreview :selectIcon=selectIcon title="pause"><tap-icon-pause></tap-icon-pause></IconPreview>
		<IconPreview :selectIcon=selectIcon title="pencil-line"><tap-icon-pencil-line></tap-icon-pencil-line></IconPreview>
		<IconPreview :selectIcon=selectIcon title="pencil-line-fill"><tap-icon-pencil-line-fill></tap-icon-pencil-line-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="person"><tap-icon-person></tap-icon-person></IconPreview>
		<IconPreview :selectIcon=selectIcon title="person-1"><tap-icon-person-1></tap-icon-person-1></IconPreview>
		<IconPreview :selectIcon=selectIcon title="person-fill"><tap-icon-person-fill></tap-icon-person-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="person-fill-1"><tap-icon-person-fill-1></tap-icon-person-fill-1></IconPreview>
		<IconPreview :selectIcon=selectIcon title="person-in-wheelchair"><tap-icon-person-in-wheelchair></tap-icon-person-in-wheelchair></IconPreview>
		<IconPreview :selectIcon=selectIcon title="person-minus"><tap-icon-person-minus></tap-icon-person-minus></IconPreview>
		<IconPreview :selectIcon=selectIcon title="person-minus-fill"><tap-icon-person-minus-fill></tap-icon-person-minus-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="person-plus"><tap-icon-person-plus></tap-icon-person-plus></IconPreview>
		<IconPreview :selectIcon=selectIcon title="person-plus-fill"><tap-icon-person-plus-fill></tap-icon-person-plus-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="person-two"><tap-icon-person-two></tap-icon-person-two></IconPreview>
		<IconPreview :selectIcon=selectIcon title="person-two-fill"><tap-icon-person-two-fill></tap-icon-person-two-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="person-wave"><tap-icon-person-wave></tap-icon-person-wave></IconPreview>
		<IconPreview :selectIcon=selectIcon title="person-wave-fill"><tap-icon-person-wave-fill></tap-icon-person-wave-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="phone"><tap-icon-phone></tap-icon-phone></IconPreview>
		<IconPreview :selectIcon=selectIcon title="phone-fill"><tap-icon-phone-fill></tap-icon-phone-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="phone-vibrate"><tap-icon-phone-vibrate></tap-icon-phone-vibrate></IconPreview>
		<IconPreview :selectIcon=selectIcon title="phone-vibrate-fill"><tap-icon-phone-vibrate-fill></tap-icon-phone-vibrate-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="pin"><tap-icon-pin></tap-icon-pin></IconPreview>
		<IconPreview :selectIcon=selectIcon title="pin-cross"><tap-icon-pin-cross></tap-icon-pin-cross></IconPreview>
		<IconPreview :selectIcon=selectIcon title="pin-cross-fill"><tap-icon-pin-cross-fill></tap-icon-pin-cross-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="pin-fill"><tap-icon-pin-fill></tap-icon-pin-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="pin-on-map"><tap-icon-pin-on-map></tap-icon-pin-on-map></IconPreview>
		<IconPreview :selectIcon=selectIcon title="pin-on-map-fill"><tap-icon-pin-on-map-fill></tap-icon-pin-on-map-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="pin-wave"><tap-icon-pin-wave></tap-icon-pin-wave></IconPreview>
		<IconPreview :selectIcon=selectIcon title="pin-wave-fill"><tap-icon-pin-wave-fill></tap-icon-pin-wave-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="plane"><tap-icon-plane></tap-icon-plane></IconPreview>
		<IconPreview :selectIcon=selectIcon title="plane-fill"><tap-icon-plane-fill></tap-icon-plane-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="planet-earth"><tap-icon-planet-earth></tap-icon-planet-earth></IconPreview>
		<IconPreview :selectIcon=selectIcon title="play"><tap-icon-play></tap-icon-play></IconPreview>
		<IconPreview :selectIcon=selectIcon title="plus"><tap-icon-plus></tap-icon-plus></IconPreview>
		<IconPreview :selectIcon=selectIcon title="plus-fill"><tap-icon-plus-fill></tap-icon-plus-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="point-three-connected-trianglepath-line"><tap-icon-point-three-connected-trianglepath-line></tap-icon-point-three-connected-trianglepath-line></IconPreview>
		<IconPreview :selectIcon=selectIcon title="point-three-connected-trianglepath-line-fill"><tap-icon-point-three-connected-trianglepath-line-fill></tap-icon-point-three-connected-trianglepath-line-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="power"><tap-icon-power></tap-icon-power></IconPreview>
		<IconPreview :selectIcon=selectIcon title="question"><tap-icon-question></tap-icon-question></IconPreview>
		<IconPreview :selectIcon=selectIcon title="record"><tap-icon-record></tap-icon-record></IconPreview>
		<IconPreview :selectIcon=selectIcon title="rectangle-person-text"><tap-icon-rectangle-person-text></tap-icon-rectangle-person-text></IconPreview>
		<IconPreview :selectIcon=selectIcon title="rectangle-person-text-with-badge"><tap-icon-rectangle-person-text-with-badge></tap-icon-rectangle-person-text-with-badge></IconPreview>
		<IconPreview :selectIcon=selectIcon title="send-chat"><tap-icon-send-chat></tap-icon-send-chat></IconPreview>
		<IconPreview :selectIcon=selectIcon title="send-chat-fill"><tap-icon-send-chat-fill></tap-icon-send-chat-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="share"><tap-icon-share></tap-icon-share></IconPreview>
		<IconPreview :selectIcon=selectIcon title="share-fill"><tap-icon-share-fill></tap-icon-share-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="shield-tick"><tap-icon-shield-tick></tap-icon-shield-tick></IconPreview>
		<IconPreview :selectIcon=selectIcon title="shield-tick-fill"><tap-icon-shield-tick-fill></tap-icon-shield-tick-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="shopping-bag"><tap-icon-shopping-bag></tap-icon-shopping-bag></IconPreview>
		<IconPreview :selectIcon=selectIcon title="shopping-bag-fill"><tap-icon-shopping-bag-fill></tap-icon-shopping-bag-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="shopping-cart"><tap-icon-shopping-cart></tap-icon-shopping-cart></IconPreview>
		<IconPreview :selectIcon=selectIcon title="shopping-cart-fill"><tap-icon-shopping-cart-fill></tap-icon-shopping-cart-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="single-check"><tap-icon-single-check></tap-icon-single-check></IconPreview>
		<IconPreview :selectIcon=selectIcon title="siren"><tap-icon-siren></tap-icon-siren></IconPreview>
		<IconPreview :selectIcon=selectIcon title="siren-fill"><tap-icon-siren-fill></tap-icon-siren-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="slider-horizontal"><tap-icon-slider-horizontal></tap-icon-slider-horizontal></IconPreview>
		<IconPreview :selectIcon=selectIcon title="slider-horizontal-fill"><tap-icon-slider-horizontal-fill></tap-icon-slider-horizontal-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="spark"><tap-icon-spark></tap-icon-spark></IconPreview>
		<IconPreview :selectIcon=selectIcon title="spark-fill"><tap-icon-spark-fill></tap-icon-spark-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="spark-small"><tap-icon-spark-small></tap-icon-spark-small></IconPreview>
		<IconPreview :selectIcon=selectIcon title="spark-small-fill"><tap-icon-spark-small-fill></tap-icon-spark-small-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="spark-three"><tap-icon-spark-three></tap-icon-spark-three></IconPreview>
		<IconPreview :selectIcon=selectIcon title="spark-three-fill"><tap-icon-spark-three-fill></tap-icon-spark-three-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="speaker-cross"><tap-icon-speaker-cross></tap-icon-speaker-cross></IconPreview>
		<IconPreview :selectIcon=selectIcon title="speaker-exclamation"><tap-icon-speaker-exclamation></tap-icon-speaker-exclamation></IconPreview>
		<IconPreview :selectIcon=selectIcon title="speaker-wave"><tap-icon-speaker-wave></tap-icon-speaker-wave></IconPreview>
		<IconPreview :selectIcon=selectIcon title="spiral-dot-two"><tap-icon-spiral-dot-two></tap-icon-spiral-dot-two></IconPreview>
		<IconPreview :selectIcon=selectIcon title="square-above-squares"><tap-icon-square-above-squares></tap-icon-square-above-squares></IconPreview>
		<IconPreview :selectIcon=selectIcon title="square-fill"><tap-icon-square-fill></tap-icon-square-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="square-fill-1"><tap-icon-square-fill-1></tap-icon-square-fill-1></IconPreview>
		<IconPreview :selectIcon=selectIcon title="square-fill-2"><tap-icon-square-fill-2></tap-icon-square-fill-2></IconPreview>
		<IconPreview :selectIcon=selectIcon title="square-fill-3"><tap-icon-square-fill-3></tap-icon-square-fill-3></IconPreview>
		<IconPreview :selectIcon=selectIcon title="square-fill-4"><tap-icon-square-fill-4></tap-icon-square-fill-4></IconPreview>
		<IconPreview :selectIcon=selectIcon title="square-fill-5"><tap-icon-square-fill-5></tap-icon-square-fill-5></IconPreview>
		<IconPreview :selectIcon=selectIcon title="square-fill-6"><tap-icon-square-fill-6></tap-icon-square-fill-6></IconPreview>
		<IconPreview :selectIcon=selectIcon title="square-fill-7"><tap-icon-square-fill-7></tap-icon-square-fill-7></IconPreview>
		<IconPreview :selectIcon=selectIcon title="square-fill-8"><tap-icon-square-fill-8></tap-icon-square-fill-8></IconPreview>
		<IconPreview :selectIcon=selectIcon title="square-fill-9"><tap-icon-square-fill-9></tap-icon-square-fill-9></IconPreview>
		<IconPreview :selectIcon=selectIcon title="square-four"><tap-icon-square-four></tap-icon-square-four></IconPreview>
		<IconPreview :selectIcon=selectIcon title="square-four-fill"><tap-icon-square-four-fill></tap-icon-square-four-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="square-grid"><tap-icon-square-grid></tap-icon-square-grid></IconPreview>
		<IconPreview :selectIcon=selectIcon title="square-grid-fill"><tap-icon-square-grid-fill></tap-icon-square-grid-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="square-grid-rounded"><tap-icon-square-grid-rounded></tap-icon-square-grid-rounded></IconPreview>
		<IconPreview :selectIcon=selectIcon title="square-grid-rounded-fill"><tap-icon-square-grid-rounded-fill></tap-icon-square-grid-rounded-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="square-more"><tap-icon-square-more></tap-icon-square-more></IconPreview>
		<IconPreview :selectIcon=selectIcon title="square-more-fill"><tap-icon-square-more-fill></tap-icon-square-more-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="square-outline-1"><tap-icon-square-outline-1></tap-icon-square-outline-1></IconPreview>
		<IconPreview :selectIcon=selectIcon title="square-outline-2"><tap-icon-square-outline-2></tap-icon-square-outline-2></IconPreview>
		<IconPreview :selectIcon=selectIcon title="square-outline-3"><tap-icon-square-outline-3></tap-icon-square-outline-3></IconPreview>
		<IconPreview :selectIcon=selectIcon title="square-outline-4"><tap-icon-square-outline-4></tap-icon-square-outline-4></IconPreview>
		<IconPreview :selectIcon=selectIcon title="square-outline-5"><tap-icon-square-outline-5></tap-icon-square-outline-5></IconPreview>
		<IconPreview :selectIcon=selectIcon title="square-outline-6"><tap-icon-square-outline-6></tap-icon-square-outline-6></IconPreview>
		<IconPreview :selectIcon=selectIcon title="square-outline-7"><tap-icon-square-outline-7></tap-icon-square-outline-7></IconPreview>
		<IconPreview :selectIcon=selectIcon title="square-outline-8"><tap-icon-square-outline-8></tap-icon-square-outline-8></IconPreview>
		<IconPreview :selectIcon=selectIcon title="square-outline-9"><tap-icon-square-outline-9></tap-icon-square-outline-9></IconPreview>
		<IconPreview :selectIcon=selectIcon title="square-person"><tap-icon-square-person></tap-icon-square-person></IconPreview>
		<IconPreview :selectIcon=selectIcon title="square-person-fill"><tap-icon-square-person-fill></tap-icon-square-person-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="star"><tap-icon-star></tap-icon-star></IconPreview>
		<IconPreview :selectIcon=selectIcon title="star-fill"><tap-icon-star-fill></tap-icon-star-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="steer"><tap-icon-steer></tap-icon-steer></IconPreview>
		<IconPreview :selectIcon=selectIcon title="steer-fill"><tap-icon-steer-fill></tap-icon-steer-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="sticky-note"><tap-icon-sticky-note></tap-icon-sticky-note></IconPreview>
		<IconPreview :selectIcon=selectIcon title="sticky-note-fill"><tap-icon-sticky-note-fill></tap-icon-sticky-note-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="store"><tap-icon-store></tap-icon-store></IconPreview>
		<IconPreview :selectIcon=selectIcon title="store-fill"><tap-icon-store-fill></tap-icon-store-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="sun"><tap-icon-sun></tap-icon-sun></IconPreview>
		<IconPreview :selectIcon=selectIcon title="sun-fill"><tap-icon-sun-fill></tap-icon-sun-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="tapsi-logo"><tap-icon-tapsi-logo></tap-icon-tapsi-logo></IconPreview>
		<IconPreview :selectIcon=selectIcon title="target"><tap-icon-target></tap-icon-target></IconPreview>
		<IconPreview :selectIcon=selectIcon title="target-fill"><tap-icon-target-fill></tap-icon-target-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="target-slash"><tap-icon-target-slash></tap-icon-target-slash></IconPreview>
		<IconPreview :selectIcon=selectIcon title="telephone"><tap-icon-telephone></tap-icon-telephone></IconPreview>
		<IconPreview :selectIcon=selectIcon title="telephone-fill"><tap-icon-telephone-fill></tap-icon-telephone-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="thumb-down"><tap-icon-thumb-down></tap-icon-thumb-down></IconPreview>
		<IconPreview :selectIcon=selectIcon title="thumb-down-fill"><tap-icon-thumb-down-fill></tap-icon-thumb-down-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="thumb-up"><tap-icon-thumb-up></tap-icon-thumb-up></IconPreview>
		<IconPreview :selectIcon=selectIcon title="thumb-up-fill"><tap-icon-thumb-up-fill></tap-icon-thumb-up-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="timer"><tap-icon-timer></tap-icon-timer></IconPreview>
		<IconPreview :selectIcon=selectIcon title="timer-fill"><tap-icon-timer-fill></tap-icon-timer-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="traffic-light"><tap-icon-traffic-light></tap-icon-traffic-light></IconPreview>
		<IconPreview :selectIcon=selectIcon title="traffic-light-fill"><tap-icon-traffic-light-fill></tap-icon-traffic-light-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="trash"><tap-icon-trash></tap-icon-trash></IconPreview>
		<IconPreview :selectIcon=selectIcon title="trash-fill"><tap-icon-trash-fill></tap-icon-trash-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="triangle-exclamation"><tap-icon-triangle-exclamation></tap-icon-triangle-exclamation></IconPreview>
		<IconPreview :selectIcon=selectIcon title="triangle-exclamation-fill"><tap-icon-triangle-exclamation-fill></tap-icon-triangle-exclamation-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="ufo"><tap-icon-ufo></tap-icon-ufo></IconPreview>
		<IconPreview :selectIcon=selectIcon title="ufo-fill"><tap-icon-ufo-fill></tap-icon-ufo-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="video-two"><tap-icon-video-two></tap-icon-video-two></IconPreview>
		<IconPreview :selectIcon=selectIcon title="video-two-fill"><tap-icon-video-two-fill></tap-icon-video-two-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="wallet"><tap-icon-wallet></tap-icon-wallet></IconPreview>
		<IconPreview :selectIcon=selectIcon title="wallet-fill"><tap-icon-wallet-fill></tap-icon-wallet-fill></IconPreview>
		<IconPreview :selectIcon=selectIcon title="wallet-swap"><tap-icon-wallet-swap></tap-icon-wallet-swap></IconPreview>
		<IconPreview :selectIcon=selectIcon title="wifi"><tap-icon-wifi></tap-icon-wifi></IconPreview>
		<IconPreview :selectIcon=selectIcon title="wifi-slash"><tap-icon-wifi-slash></tap-icon-wifi-slash></IconPreview>

  </div>
</template>

<script setup>
import '../../src/lit/icons';
import IconPreview from './IconPreview.vue';

defineProps({
  selectIcon: String | null,
})
</script>

<style scoped>
  .icon-grid {
    display: flex;
    flex-wrap: wrap;
    gap: 16px;
  }
</style>
